name: "Setup mdtest"
description: "Install the mdtest CLI and add it to PATH."
author: "UpCloudLtd"

inputs:
  version:
    description: "Version of mdtest to install (e.g. v0.3.1). Avoid 'latest' for reproducible builds."
    required: false
    default: "latest"
  install-go:
    description: "Whether to install Go toolchain (true/false)."
    required: false
    default: "false"
  go-version:
    description: "Go version to install if install-go=true (e.g. '1.24.x')."
    required: false
    default: "1.24.x"

outputs:
  gobin:
    description: "Directory where mdtest was installed."
    value: ${{ steps.install.outputs.gobin }}

runs:
  using: "composite"
  steps:
    - name: Setup Go
      if: ${{ inputs.install-go == 'true' }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
        check-latest: true

    - name: Install mdtest
      id: install
      shell: bash
      run: |
        set -euo pipefail

        # Deterministic install location inside workspace
        GOBIN="${GITHUB_WORKSPACE}/.tools/bin"
        mkdir -p "${GOBIN}"

        echo "gobin=${GOBIN}" >> "$GITHUB_OUTPUT"
        echo "${GOBIN}" >> "${GITHUB_PATH}"

        echo "Installing mdtest@${{ inputs.version }}"
        GOBIN="${GOBIN}" go install github.com/UpCloudLtd/mdtest@${{ inputs.version }}

        command -v mdtest >/dev/null 2>&1
        echo "mdtest installed at: $(command -v mdtest)"
