version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - depguard
    - dogsled
    - dupl
    - dupword
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - goconst
    - gocritic
    - godot
    - gomoddirectives
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - importas
    - interfacebloat
    - loggercheck
    - makezero
    - mirror
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck
    - zerologlint
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/pkg/errors
              desc: use stdlib instead
    errcheck:
      check-type-assertions: true
    gocritic:
      disabled-checks:
        - commentFormatting
        - hugeParam
        - rangeValCopy
        - rangeExprCopy
      enabled-tags:
        - performance
      settings:
        captLocal:
          paramsOnly: false
    importas:
      alias:
        - pkg: github.com/pkg/errors
          alias: pkgerrors
      no-unaliased: true
    nolintlint:
      require-explanation: true
      require-specific: true
    reassign:
      patterns:
        - .*
    revive:
      rules:
        - name: var-naming
          arguments:
            - []
            - - ACME
              - AMQP
              - BGP
              - CA
              - CIDR
              - CN
              - CSV
              - DB
              - DCMI
              - DHCP
              - DN
              - DSA
              - ECDSA
              - EMA
              - EVI
              - EVPN
              - FIFO
              - FRU
              - GID
              - GPU
              - IB
              - IOPS
              - IPMI
              - JWT
              - KV
              - LAN
              - LFU
              - LIFO
              - LRU
              - MAC
              - MS
              - NIC
              - PDF
              - PKI
              - PSU
              - PTR
              - REST
              - RSA
              - RTP
              - RX
              - SCSI
              - SDN
              - SHA
              - SIP
              - SPOE
              - SSD
              - TS
              - TSIG
              - TSV
              - TTL
              - TX
              - TXN
              - ULID
              - VAT
              - VCPU
              - VIP
              - VLAN
              - VRF
            - - skip-package-name-checks: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gochecknoglobals
          - gochecknoinits
        path: cmd/
      - linters:
          - bodyclose
          - funlen
          - noctx
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true
formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
